### PR TITLE
add: png format

### PR DESCRIPTION
**Pull request by zhuangya**
i try to implement the png format but here are some known issues:

- i need fluentdesk/fluent-themes#17 to be merged first
- phantom solution is kind of slow, but i can not find anyother methods
- figure a way to test?

### CODE REVIEW

**Comment by robertmain** [comment]
:+1:

**Comment by Cardly596** [comment]
Hello

**Comment by hacksalot** [comment]
Awesome work @zhuangya! -- still playing a bit of catch up, we lost power for most of the day with the rain. The Phantom solution, slow or not, actually fits here because Phantom also offers PDF generation, of a different flavor than wkhtmltopdf. So it's a bit of a kill two birds with one stone sort of thing.

@Cardly596 Hi.

**Comment by robertmain** [comment]
So are you thinking of dropping wkhtmltopdf in favour of phantom in that case?

**Comment by zhuangya** [comment]
> because Phantom also offers PDF generation

@hacksalot yes, that's pretty easy to extend png and pdf version for the `html-png-generator.js`


> So are you thinking of dropping wkhtmltopdf in favour of phantom in that case? if so, that would be pretty neat because it would remove the native dependency requirement

+1 for `phantom`

**Comment by hacksalot** [comment]
Sounds good. Let's add Phantom PDF support (+1). We've actually still got some orphaned Phantom PDF code [floating around](https://github.com/hacksalot/HackMyResume/blob/dev/src/gen/html-pdf-generator.js#L58-L80):

```javascript
// function pdf_phantom() {
  //   require('phantom').create( function( ph ) {
  //     ph.createPage( function( page ) {
  //       page.setContent( markup );
  //       page.set('paperSize', {
  //         format: 'A4',
  //         orientation: 'portrait',
  //         margin: '1cm'
  //       });
  //       page.set("viewportSize", {
  //         width: 1024, // TODO: option-ify
  //         height: 768 // TODO: Use "A" sizes
  //       });
  //       page.set('onLoadFinished', function(success) {
  //         page.render( fOut );
  //         ph.exit();
  //       });
  //     },
  //     { dnodeOpts: {  weak: false   } } );
  //   });
  // }
```

wkhtmltopdf is now an optional dependency and its absence gracefully handled per @robertmain's #51 so the binary install is no longer necessary unless you're actually using wkhtmltopdf. Which means we can offer both solutions and, down the road, the ultimate solution: a PDF generation route via LaTeX or other non-HTML-driven programmatic generator. HTML-driven PDFs are quick and easy but in my testing they haven't yielded the kind of crystal clear PDF goodness you can get out of a LaTeX stack or a programmatic generator. Something to keep in mind..

**Comment by zhuangya** [comment]
i think we can setup a priority for the pdf/png generator like:

LaTeX > phantomjs > wkhtmltopdf

since LaTeX is something huge to install

**Comment by zhuangya** [comment]
about how LaTeX generate pdf and png: http://tex.stackexchange.com/a/11880

**Comment by robertmain** [comment]
Except then the PDF generation depends on the latex generation(i.e: you have to generate the resume as latex, then use that to create a PDF). That feels wrong somehow for the same reason that unit tests shouldn't depend on one another..

**Comment by hacksalot** [comment]
Good points both. To me, as long as we can protect users from the messy generative workflow around PDFs, by encapsulating it into a box with a well-defined interface, we're free to use whatever method under the hood we want. Partly too it depends on the theme: a theme that doesn't explicitly declare PDF support should still be able to generate a PDF, provided it has an HTML or Word format. A theme that *explicitly* declares PDF support, which it could do by declaring an HTML or Tex template targeting PDF, presumably knows what it's doing.

**Comment by hacksalot** [comment]
@zhuangya Integrating this with latest from `dev`. Stay tuned.

**Comment by zhuangya** [comment]
sure thing.

but i need to sleep now, it's 2:00 AM in GMT +8 now :)

**Pull request merged**
