### PR TITLE
Implements private fields as requested in #88

### PR DESCRIPTION
**Pull request by daniele-rapagnani**
I've implemented private fields as described in #88.

The `parseJSON` method of the `JRSResume` and of the `FreshResume` acts the same as before unless a `private` option is specified.
The `BUILD` and `ANALYZE` verb exclude private fields by default. They can be included using the new `--private` option.

I have two tests failing: one from the CLI tests and the exemplars one. I noticed they are failing on the `dev` branch too, so I didn't fix them on this feature branch. I guess they will be addressed on `dev`, am I correct?

Let me know if I missed something.

### CODE REVIEW

**Comment by hacksalot** [comment]
Nice work @daniele-rapagnani! Will merge shortly.

**Comment by hacksalot** [comment]
This is the first HackMyResume PR that has targeted `dev`. There should be a door prize or something for that. :trophy: 

CC @robertmain

**Comment by robertmain** [comment]
You called? :)

**Comment by hacksalot** [comment]
Looks clean. Nice work @daniele-rapagnani!

@robertmain You were the original requestor (#88) just a heads up.

**Comment by robertmain** [comment]
Ah right, yeah :) Nice to see it implemented! - :+1: @daniele-rapagnani

**Comment by josivan** [comment]
Is this feature working? I'm using the template available [here](https://github.com/fluentdesk/jane-q-fullstacker/blob/master/resume/jane-resume.json) and the private fields are still being generated. I'm using version 1.9.0-beta

**Pull request merged**
