### PR TITLE
move tests => test

### PR DESCRIPTION
**Pull request by zhuangya**
rel #41

### CODE REVIEW

**Comment by zhuangya** [comment]
i have to say, this is weird ...

why i can pass the tests by running `mocha`
and i can not pass the test by running `grunt test`

btw: i don't install `wkhtmltopdf` on my computer

also, according to the previous discussion #60 maybe ditch `wkhtmltopdf` now?
in that way we can pass travis-ci too.

**Comment by hacksalot** [comment]
Travis CI issues should be resolved after merging `dev` to `master` and then going forward we can work off `dev` or the latest release branch. Thanks! I like the idea of a LaTeX -> Phantom -> wkhtmltopdf fallback for the PDF generation, again, provided we can support wkhtmltopdf when it's present, but not require it when it's not.

**Comment by hacksalot** [comment]
Hey @zhuangya Happy New Year. Is this PR active? Are you experiencing any Travis issues? Thanks.

**Comment by zhuangya** [comment]
@hacksalot Happy New Year.

i rebase my topic branch onto orign/master at the time.

and then the RP only changes `.gitignore` in the project root

since `test/sandbox` is alread ignore by `test/sandbox`

i'm closing this RP

**Comment by zhuangya** [comment]
and also, travis-ci works fine as reported

**Pull request closed without merging**
