### PR TITLE
Don't do html escaping. Fix #157.

### LINKED ISSUE #157: apostrophes are rendered as &#39; for HTML and PDF artifacts
When generating a PDF or HTML document from FRESH or JSR resume apostrophes are displayed as \&\#39; in the recognition and awards section.

[resume.pdf](https://github.com/hacksalot/HackMyResume/files/226982/resume.pdf)

### PR DESCRIPTION
**Pull request by ryneeverett**

### CODE REVIEW

**Comment by peternowee** [comment]
Removing the Handlebars HTML escaping does of course increase the risk of cross-site scripting (XSS).

Also, it seems there is some double escaping going on. For example, without your patch, the single quote or apostrophe (`'`) ends up in the intermediary `.pdf.html` file as `&amp;#39;`, whereas if it was escaped only once, it would have been `&#39;`, which then would have made it even render back to the apostrophe correctly by the HTML-to-PDF renderer. So somewhere the first ampersand (`&`) of `&#39;` is escaped again.

I assume the Handlebars escaping comes somewhere at the end, so second, and there is a first escaping done before that. Perhaps related to the parsing of Markdown/HTML formatting allowed in text fields [as described here](https://github.com/hacksalot/HackMyResume/issues/59#issuecomment-167717324) for example?

**Comment by ryneeverett** [comment]
@peternowee I'm not sure I see how XSS is relevant here. Isn't all input trusted?

Your theory of double-escaping is worth further investigation and might lead to a better solution than this patch.

**Comment by peternowee** [comment]
> I'm not sure I see how XSS is relevant here. Isn't all input trusted?

Usually, yes. It was more a general remark that we should consider this. As an example where input might not be fully trusted, I can imagine a job agency or corporate recruitment department receiving and storing candidate resumes in JSON and converting them through this software to HTML for display in their browsers.

Btw, another thing I noticed about that other (not-Handlebars) escaping, is that it escapes single quotes/apostrophes (`'`) and ampersands (`&`), but not angle brackets (`<` and `>`) and single quotes inside tags made by angle brackets. Two examples, both with Handlebars escaping turned off:

**Example 1**
JSON input:
```json
"role": "Foreman<script type='text/javascript'>alert('123');</script>"
```
HTML output:
```html
<em>Foreman<script type='text/javascript'>alert(&#39;123&#39;);</script></em>
```
Browser result (FF 45.7.0):
Nothing happens, because of the `&#39;` instead of `'`.

**Example 2**
However, when not using single quotes in the alert, it does execute:
JSON input:
```json
"role": "Foreman<script type='text/javascript'>alert(123);</script>"
```
HTML output:
```html
<em>Foreman<script type='text/javascript'>alert(123);</script></em>
```
Browser result (FF 45.7.0):
A popup showing "123".

> Your theory of double-escaping is worth further investigation and might lead to a better solution than this patch.

Thanks. Not sure if I have time to investigate further myself though.

**Comment by hacksalot** [comment]
Good thoughts. I've accepted the PR and will update with an option to disable HTML escaping globally for now.  Beyond that it seems like we need finer-grained control over encoding.

Using `{{{ }}}` in the template files is an option (we do that for `<a href="{{{ blah }}}">` for example) but if we do this across the board we run into a situation where a user can break the resume format by using any arbitrarily meaningful character in the resume text, and what exactly is "meaningful" depends on the underlying format. For example, using a `<` or `>` (unescaped) in any XML- or HTML-backed resume would probably invalidate the document.

**Pull request merged**
